/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shashidhar' at '7/21/16 2:45 PM' with Gradle 2.14
 *
 * @author shashidhar, @date 7/21/16 2:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
